doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URI)%'
        charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            numeric_functions:
                round: App\DoctrineFunctions\Round
            datetime_functions:
                date_format: App\DoctrineFunctions\DateFormat